name: Lighthouse

on:
  workflow_run:
    workflows: CI/CD
    types: completed
    branches: main

jobs:
  audit-prod:
    name: Run Lighthouse audits on the production website
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Run Lighthouse audits
        uses: ./.github/actions/lighthouse
        id: lighthouse
        with:
          config-path: ./lighthouse-prod.config.json
          root-url: https://corentin-regent.github.io/portfolio/
          artifact-name: lighthouse-results-prod

      - name: Generate Lighthouse report
        if: success() || failure()
        run: node scripts/update-lighthouse-report.js '${{ steps.lighthouse.outputs.results-path }}/manifest.json'

      - name: Pull eventual changes
        if: success() || failure()
        run: git pull

      - name: Commit Lighthouse report
        if: success() || failure()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Refresh Lighthouse report [skip ci]'
          file_pattern: docs/lighthouse-report.png
